// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/rpc/error_details.proto

package org.apache.ratis.shaded.com.google.rpc;

public interface QuotaFailureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.rpc.QuotaFailure)
    org.apache.ratis.shaded.com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Describes all quota violations.
   * </pre>
   *
   * <code>repeated .google.rpc.QuotaFailure.Violation violations = 1;</code>
   */
  java.util.List<org.apache.ratis.shaded.com.google.rpc.QuotaFailure.Violation> 
      getViolationsList();
  /**
   * <pre>
   * Describes all quota violations.
   * </pre>
   *
   * <code>repeated .google.rpc.QuotaFailure.Violation violations = 1;</code>
   */
  org.apache.ratis.shaded.com.google.rpc.QuotaFailure.Violation getViolations(int index);
  /**
   * <pre>
   * Describes all quota violations.
   * </pre>
   *
   * <code>repeated .google.rpc.QuotaFailure.Violation violations = 1;</code>
   */
  int getViolationsCount();
  /**
   * <pre>
   * Describes all quota violations.
   * </pre>
   *
   * <code>repeated .google.rpc.QuotaFailure.Violation violations = 1;</code>
   */
  java.util.List<? extends org.apache.ratis.shaded.com.google.rpc.QuotaFailure.ViolationOrBuilder> 
      getViolationsOrBuilderList();
  /**
   * <pre>
   * Describes all quota violations.
   * </pre>
   *
   * <code>repeated .google.rpc.QuotaFailure.Violation violations = 1;</code>
   */
  org.apache.ratis.shaded.com.google.rpc.QuotaFailure.ViolationOrBuilder getViolationsOrBuilder(
      int index);
}
