// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/config_change.proto

package org.apache.ratis.shaded.com.google.api;

public interface AdviceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.api.Advice)
    org.apache.ratis.shaded.com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Useful description for why this advice was applied and what actions should
   * be taken to mitigate any implied risks.
   * </pre>
   *
   * <code>string description = 2;</code>
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * Useful description for why this advice was applied and what actions should
   * be taken to mitigate any implied risks.
   * </pre>
   *
   * <code>string description = 2;</code>
   */
  org.apache.ratis.shaded.com.google.protobuf.ByteString
      getDescriptionBytes();
}
