// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/annotations.proto

package org.apache.ratis.shaded.com.google.api;

public final class AnnotationsProto {
  private AnnotationsProto() {}
  public static void registerAllExtensions(
      org.apache.ratis.shaded.com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(org.apache.ratis.shaded.com.google.api.AnnotationsProto.http);
  }

  public static void registerAllExtensions(
      org.apache.ratis.shaded.com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (org.apache.ratis.shaded.com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int HTTP_FIELD_NUMBER = 72295728;
  /**
   * <pre>
   * See `HttpRule`.
   * </pre>
   *
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    org.apache.ratis.shaded.com.google.protobuf.GeneratedMessage.GeneratedExtension<
      org.apache.ratis.shaded.com.google.protobuf.DescriptorProtos.MethodOptions,
      org.apache.ratis.shaded.com.google.api.HttpRule> http = org.apache.ratis.shaded.com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        org.apache.ratis.shaded.com.google.api.HttpRule.class,
        org.apache.ratis.shaded.com.google.api.HttpRule.getDefaultInstance());

  public static org.apache.ratis.shaded.com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  org.apache.ratis.shaded.com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034google/api/annotations.proto\022\ngoogle.a" +
      "pi\032\025google/api/http.proto\032 google/protob" +
      "uf/descriptor.proto:E\n\004http\022\036.google.pro" +
      "tobuf.MethodOptions\030\260\312\274\" \001(\0132\024.google.ap" +
      "i.HttpRuleBn\n\016com.google.apiB\020Annotation" +
      "sProtoP\001ZAgoogle.golang.org/genproto/goo" +
      "gleapis/api/annotations;annotations\242\002\004GA" +
      "PIb\006proto3"
    };
    org.apache.ratis.shaded.com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new org.apache.ratis.shaded.com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public org.apache.ratis.shaded.com.google.protobuf.ExtensionRegistry assignDescriptors(
              org.apache.ratis.shaded.com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    org.apache.ratis.shaded.com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new org.apache.ratis.shaded.com.google.protobuf.Descriptors.FileDescriptor[] {
          org.apache.ratis.shaded.com.google.api.HttpProto.getDescriptor(),
          org.apache.ratis.shaded.com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
    http.internalInit(descriptor.getExtensions().get(0));
    org.apache.ratis.shaded.com.google.api.HttpProto.getDescriptor();
    org.apache.ratis.shaded.com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
