// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/auth.proto

package org.apache.ratis.shaded.com.google.api;

public interface AuthenticationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.api.Authentication)
    org.apache.ratis.shaded.com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A list of authentication rules that apply to individual API methods.
   * **NOTE:** All service configuration rules follow "last one wins" order.
   * </pre>
   *
   * <code>repeated .google.api.AuthenticationRule rules = 3;</code>
   */
  java.util.List<org.apache.ratis.shaded.com.google.api.AuthenticationRule> 
      getRulesList();
  /**
   * <pre>
   * A list of authentication rules that apply to individual API methods.
   * **NOTE:** All service configuration rules follow "last one wins" order.
   * </pre>
   *
   * <code>repeated .google.api.AuthenticationRule rules = 3;</code>
   */
  org.apache.ratis.shaded.com.google.api.AuthenticationRule getRules(int index);
  /**
   * <pre>
   * A list of authentication rules that apply to individual API methods.
   * **NOTE:** All service configuration rules follow "last one wins" order.
   * </pre>
   *
   * <code>repeated .google.api.AuthenticationRule rules = 3;</code>
   */
  int getRulesCount();
  /**
   * <pre>
   * A list of authentication rules that apply to individual API methods.
   * **NOTE:** All service configuration rules follow "last one wins" order.
   * </pre>
   *
   * <code>repeated .google.api.AuthenticationRule rules = 3;</code>
   */
  java.util.List<? extends org.apache.ratis.shaded.com.google.api.AuthenticationRuleOrBuilder> 
      getRulesOrBuilderList();
  /**
   * <pre>
   * A list of authentication rules that apply to individual API methods.
   * **NOTE:** All service configuration rules follow "last one wins" order.
   * </pre>
   *
   * <code>repeated .google.api.AuthenticationRule rules = 3;</code>
   */
  org.apache.ratis.shaded.com.google.api.AuthenticationRuleOrBuilder getRulesOrBuilder(
      int index);

  /**
   * <pre>
   * Defines a set of authentication providers that a service supports.
   * </pre>
   *
   * <code>repeated .google.api.AuthProvider providers = 4;</code>
   */
  java.util.List<org.apache.ratis.shaded.com.google.api.AuthProvider> 
      getProvidersList();
  /**
   * <pre>
   * Defines a set of authentication providers that a service supports.
   * </pre>
   *
   * <code>repeated .google.api.AuthProvider providers = 4;</code>
   */
  org.apache.ratis.shaded.com.google.api.AuthProvider getProviders(int index);
  /**
   * <pre>
   * Defines a set of authentication providers that a service supports.
   * </pre>
   *
   * <code>repeated .google.api.AuthProvider providers = 4;</code>
   */
  int getProvidersCount();
  /**
   * <pre>
   * Defines a set of authentication providers that a service supports.
   * </pre>
   *
   * <code>repeated .google.api.AuthProvider providers = 4;</code>
   */
  java.util.List<? extends org.apache.ratis.shaded.com.google.api.AuthProviderOrBuilder> 
      getProvidersOrBuilderList();
  /**
   * <pre>
   * Defines a set of authentication providers that a service supports.
   * </pre>
   *
   * <code>repeated .google.api.AuthProvider providers = 4;</code>
   */
  org.apache.ratis.shaded.com.google.api.AuthProviderOrBuilder getProvidersOrBuilder(
      int index);
}
