// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/wrappers.proto

package org.apache.ratis.shaded.com.google.protobuf;

public interface DoubleValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.DoubleValue)
    org.apache.ratis.shaded.com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The double value.
   * </pre>
   *
   * <code>double value = 1;</code>
   */
  double getValue();
}
