// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/api.proto

package org.apache.ratis.shaded.com.google.protobuf;

public interface MixinOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.Mixin)
    org.apache.ratis.shaded.com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The fully qualified name of the interface which is included.
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * The fully qualified name of the interface which is included.
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  org.apache.ratis.shaded.com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * If non-empty specifies a path under which inherited HTTP paths
   * are rooted.
   * </pre>
   *
   * <code>string root = 2;</code>
   */
  java.lang.String getRoot();
  /**
   * <pre>
   * If non-empty specifies a path under which inherited HTTP paths
   * are rooted.
   * </pre>
   *
   * <code>string root = 2;</code>
   */
  org.apache.ratis.shaded.com.google.protobuf.ByteString
      getRootBytes();
}
