// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hadoop.proto

package org.apache.ratis.shaded.proto.hadoop;

public final class HadoopProtos {
  private HadoopProtos() {}
  public static void registerAllExtensions(
      org.apache.ratis.shaded.com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      org.apache.ratis.shaded.com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (org.apache.ratis.shaded.com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf service {@code ratis.hadoop.CombinedClientProtocolService}
   */
  public static abstract class CombinedClientProtocolService
      implements org.apache.ratis.shaded.com.google.protobuf.Service {
    protected CombinedClientProtocolService() {}

    public interface Interface {
      /**
       * <code>rpc submitClientRequest(.ratis.common.RaftClientRequestProto) returns (.ratis.common.RaftClientReplyProto);</code>
       */
      public abstract void submitClientRequest(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.RaftClientRequestProto request,
          org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto> done);

      /**
       * <code>rpc setConfiguration(.ratis.common.SetConfigurationRequestProto) returns (.ratis.common.RaftClientReplyProto);</code>
       */
      public abstract void setConfiguration(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.SetConfigurationRequestProto request,
          org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto> done);

      /**
       * <code>rpc reinitialize(.ratis.common.ReinitializeRequestProto) returns (.ratis.common.RaftClientReplyProto);</code>
       */
      public abstract void reinitialize(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.ReinitializeRequestProto request,
          org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto> done);

      /**
       * <code>rpc serverInformation(.ratis.common.ServerInformationRequestProto) returns (.ratis.common.ServerInformationReplyProto);</code>
       */
      public abstract void serverInformation(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.ServerInformationRequestProto request,
          org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.ServerInformationReplyProto> done);

    }

    public static org.apache.ratis.shaded.com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new CombinedClientProtocolService() {
        @java.lang.Override
        public  void submitClientRequest(
            org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
            org.apache.ratis.shaded.proto.RaftProtos.RaftClientRequestProto request,
            org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto> done) {
          impl.submitClientRequest(controller, request, done);
        }

        @java.lang.Override
        public  void setConfiguration(
            org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
            org.apache.ratis.shaded.proto.RaftProtos.SetConfigurationRequestProto request,
            org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto> done) {
          impl.setConfiguration(controller, request, done);
        }

        @java.lang.Override
        public  void reinitialize(
            org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
            org.apache.ratis.shaded.proto.RaftProtos.ReinitializeRequestProto request,
            org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto> done) {
          impl.reinitialize(controller, request, done);
        }

        @java.lang.Override
        public  void serverInformation(
            org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
            org.apache.ratis.shaded.proto.RaftProtos.ServerInformationRequestProto request,
            org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.ServerInformationReplyProto> done) {
          impl.serverInformation(controller, request, done);
        }

      };
    }

    public static org.apache.ratis.shaded.com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new org.apache.ratis.shaded.com.google.protobuf.BlockingService() {
        public final org.apache.ratis.shaded.com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final org.apache.ratis.shaded.com.google.protobuf.Message callBlockingMethod(
            org.apache.ratis.shaded.com.google.protobuf.Descriptors.MethodDescriptor method,
            org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
            org.apache.ratis.shaded.com.google.protobuf.Message request)
            throws org.apache.ratis.shaded.com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.submitClientRequest(controller, (org.apache.ratis.shaded.proto.RaftProtos.RaftClientRequestProto)request);
            case 1:
              return impl.setConfiguration(controller, (org.apache.ratis.shaded.proto.RaftProtos.SetConfigurationRequestProto)request);
            case 2:
              return impl.reinitialize(controller, (org.apache.ratis.shaded.proto.RaftProtos.ReinitializeRequestProto)request);
            case 3:
              return impl.serverInformation(controller, (org.apache.ratis.shaded.proto.RaftProtos.ServerInformationRequestProto)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final org.apache.ratis.shaded.com.google.protobuf.Message
            getRequestPrototype(
            org.apache.ratis.shaded.com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.apache.ratis.shaded.proto.RaftProtos.RaftClientRequestProto.getDefaultInstance();
            case 1:
              return org.apache.ratis.shaded.proto.RaftProtos.SetConfigurationRequestProto.getDefaultInstance();
            case 2:
              return org.apache.ratis.shaded.proto.RaftProtos.ReinitializeRequestProto.getDefaultInstance();
            case 3:
              return org.apache.ratis.shaded.proto.RaftProtos.ServerInformationRequestProto.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final org.apache.ratis.shaded.com.google.protobuf.Message
            getResponsePrototype(
            org.apache.ratis.shaded.com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto.getDefaultInstance();
            case 1:
              return org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto.getDefaultInstance();
            case 2:
              return org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto.getDefaultInstance();
            case 3:
              return org.apache.ratis.shaded.proto.RaftProtos.ServerInformationReplyProto.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc submitClientRequest(.ratis.common.RaftClientRequestProto) returns (.ratis.common.RaftClientReplyProto);</code>
     */
    public abstract void submitClientRequest(
        org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
        org.apache.ratis.shaded.proto.RaftProtos.RaftClientRequestProto request,
        org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto> done);

    /**
     * <code>rpc setConfiguration(.ratis.common.SetConfigurationRequestProto) returns (.ratis.common.RaftClientReplyProto);</code>
     */
    public abstract void setConfiguration(
        org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
        org.apache.ratis.shaded.proto.RaftProtos.SetConfigurationRequestProto request,
        org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto> done);

    /**
     * <code>rpc reinitialize(.ratis.common.ReinitializeRequestProto) returns (.ratis.common.RaftClientReplyProto);</code>
     */
    public abstract void reinitialize(
        org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
        org.apache.ratis.shaded.proto.RaftProtos.ReinitializeRequestProto request,
        org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto> done);

    /**
     * <code>rpc serverInformation(.ratis.common.ServerInformationRequestProto) returns (.ratis.common.ServerInformationReplyProto);</code>
     */
    public abstract void serverInformation(
        org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
        org.apache.ratis.shaded.proto.RaftProtos.ServerInformationRequestProto request,
        org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.ServerInformationReplyProto> done);

    public static final
        org.apache.ratis.shaded.com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.apache.ratis.shaded.proto.hadoop.HadoopProtos.getDescriptor().getServices().get(0);
    }
    public final org.apache.ratis.shaded.com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        org.apache.ratis.shaded.com.google.protobuf.Descriptors.MethodDescriptor method,
        org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
        org.apache.ratis.shaded.com.google.protobuf.Message request,
        org.apache.ratis.shaded.com.google.protobuf.RpcCallback<
          org.apache.ratis.shaded.com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.submitClientRequest(controller, (org.apache.ratis.shaded.proto.RaftProtos.RaftClientRequestProto)request,
            org.apache.ratis.shaded.com.google.protobuf.RpcUtil.<org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto>specializeCallback(
              done));
          return;
        case 1:
          this.setConfiguration(controller, (org.apache.ratis.shaded.proto.RaftProtos.SetConfigurationRequestProto)request,
            org.apache.ratis.shaded.com.google.protobuf.RpcUtil.<org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto>specializeCallback(
              done));
          return;
        case 2:
          this.reinitialize(controller, (org.apache.ratis.shaded.proto.RaftProtos.ReinitializeRequestProto)request,
            org.apache.ratis.shaded.com.google.protobuf.RpcUtil.<org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto>specializeCallback(
              done));
          return;
        case 3:
          this.serverInformation(controller, (org.apache.ratis.shaded.proto.RaftProtos.ServerInformationRequestProto)request,
            org.apache.ratis.shaded.com.google.protobuf.RpcUtil.<org.apache.ratis.shaded.proto.RaftProtos.ServerInformationReplyProto>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final org.apache.ratis.shaded.com.google.protobuf.Message
        getRequestPrototype(
        org.apache.ratis.shaded.com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.apache.ratis.shaded.proto.RaftProtos.RaftClientRequestProto.getDefaultInstance();
        case 1:
          return org.apache.ratis.shaded.proto.RaftProtos.SetConfigurationRequestProto.getDefaultInstance();
        case 2:
          return org.apache.ratis.shaded.proto.RaftProtos.ReinitializeRequestProto.getDefaultInstance();
        case 3:
          return org.apache.ratis.shaded.proto.RaftProtos.ServerInformationRequestProto.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final org.apache.ratis.shaded.com.google.protobuf.Message
        getResponsePrototype(
        org.apache.ratis.shaded.com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto.getDefaultInstance();
        case 1:
          return org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto.getDefaultInstance();
        case 2:
          return org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto.getDefaultInstance();
        case 3:
          return org.apache.ratis.shaded.proto.RaftProtos.ServerInformationReplyProto.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        org.apache.ratis.shaded.com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends org.apache.ratis.shaded.proto.hadoop.HadoopProtos.CombinedClientProtocolService implements Interface {
      private Stub(org.apache.ratis.shaded.com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final org.apache.ratis.shaded.com.google.protobuf.RpcChannel channel;

      public org.apache.ratis.shaded.com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void submitClientRequest(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.RaftClientRequestProto request,
          org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto.getDefaultInstance(),
          org.apache.ratis.shaded.com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto.class,
            org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto.getDefaultInstance()));
      }

      public  void setConfiguration(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.SetConfigurationRequestProto request,
          org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto.getDefaultInstance(),
          org.apache.ratis.shaded.com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto.class,
            org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto.getDefaultInstance()));
      }

      public  void reinitialize(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.ReinitializeRequestProto request,
          org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(2),
          controller,
          request,
          org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto.getDefaultInstance(),
          org.apache.ratis.shaded.com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto.class,
            org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto.getDefaultInstance()));
      }

      public  void serverInformation(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.ServerInformationRequestProto request,
          org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.ServerInformationReplyProto> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(3),
          controller,
          request,
          org.apache.ratis.shaded.proto.RaftProtos.ServerInformationReplyProto.getDefaultInstance(),
          org.apache.ratis.shaded.com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.apache.ratis.shaded.proto.RaftProtos.ServerInformationReplyProto.class,
            org.apache.ratis.shaded.proto.RaftProtos.ServerInformationReplyProto.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        org.apache.ratis.shaded.com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto submitClientRequest(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.RaftClientRequestProto request)
          throws org.apache.ratis.shaded.com.google.protobuf.ServiceException;

      public org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto setConfiguration(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.SetConfigurationRequestProto request)
          throws org.apache.ratis.shaded.com.google.protobuf.ServiceException;

      public org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto reinitialize(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.ReinitializeRequestProto request)
          throws org.apache.ratis.shaded.com.google.protobuf.ServiceException;

      public org.apache.ratis.shaded.proto.RaftProtos.ServerInformationReplyProto serverInformation(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.ServerInformationRequestProto request)
          throws org.apache.ratis.shaded.com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(org.apache.ratis.shaded.com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final org.apache.ratis.shaded.com.google.protobuf.BlockingRpcChannel channel;

      public org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto submitClientRequest(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.RaftClientRequestProto request)
          throws org.apache.ratis.shaded.com.google.protobuf.ServiceException {
        return (org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto.getDefaultInstance());
      }


      public org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto setConfiguration(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.SetConfigurationRequestProto request)
          throws org.apache.ratis.shaded.com.google.protobuf.ServiceException {
        return (org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto.getDefaultInstance());
      }


      public org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto reinitialize(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.ReinitializeRequestProto request)
          throws org.apache.ratis.shaded.com.google.protobuf.ServiceException {
        return (org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto) channel.callBlockingMethod(
          getDescriptor().getMethods().get(2),
          controller,
          request,
          org.apache.ratis.shaded.proto.RaftProtos.RaftClientReplyProto.getDefaultInstance());
      }


      public org.apache.ratis.shaded.proto.RaftProtos.ServerInformationReplyProto serverInformation(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.ServerInformationRequestProto request)
          throws org.apache.ratis.shaded.com.google.protobuf.ServiceException {
        return (org.apache.ratis.shaded.proto.RaftProtos.ServerInformationReplyProto) channel.callBlockingMethod(
          getDescriptor().getMethods().get(3),
          controller,
          request,
          org.apache.ratis.shaded.proto.RaftProtos.ServerInformationReplyProto.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:ratis.hadoop.CombinedClientProtocolService)
  }

  /**
   * Protobuf service {@code ratis.hadoop.RaftServerProtocolService}
   */
  public static abstract class RaftServerProtocolService
      implements org.apache.ratis.shaded.com.google.protobuf.Service {
    protected RaftServerProtocolService() {}

    public interface Interface {
      /**
       * <code>rpc requestVote(.ratis.common.RequestVoteRequestProto) returns (.ratis.common.RequestVoteReplyProto);</code>
       */
      public abstract void requestVote(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.RequestVoteRequestProto request,
          org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.RequestVoteReplyProto> done);

      /**
       * <code>rpc appendEntries(.ratis.common.AppendEntriesRequestProto) returns (.ratis.common.AppendEntriesReplyProto);</code>
       */
      public abstract void appendEntries(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.AppendEntriesRequestProto request,
          org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.AppendEntriesReplyProto> done);

      /**
       * <code>rpc installSnapshot(.ratis.common.InstallSnapshotRequestProto) returns (.ratis.common.InstallSnapshotReplyProto);</code>
       */
      public abstract void installSnapshot(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.InstallSnapshotRequestProto request,
          org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.InstallSnapshotReplyProto> done);

    }

    public static org.apache.ratis.shaded.com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new RaftServerProtocolService() {
        @java.lang.Override
        public  void requestVote(
            org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
            org.apache.ratis.shaded.proto.RaftProtos.RequestVoteRequestProto request,
            org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.RequestVoteReplyProto> done) {
          impl.requestVote(controller, request, done);
        }

        @java.lang.Override
        public  void appendEntries(
            org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
            org.apache.ratis.shaded.proto.RaftProtos.AppendEntriesRequestProto request,
            org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.AppendEntriesReplyProto> done) {
          impl.appendEntries(controller, request, done);
        }

        @java.lang.Override
        public  void installSnapshot(
            org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
            org.apache.ratis.shaded.proto.RaftProtos.InstallSnapshotRequestProto request,
            org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.InstallSnapshotReplyProto> done) {
          impl.installSnapshot(controller, request, done);
        }

      };
    }

    public static org.apache.ratis.shaded.com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new org.apache.ratis.shaded.com.google.protobuf.BlockingService() {
        public final org.apache.ratis.shaded.com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final org.apache.ratis.shaded.com.google.protobuf.Message callBlockingMethod(
            org.apache.ratis.shaded.com.google.protobuf.Descriptors.MethodDescriptor method,
            org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
            org.apache.ratis.shaded.com.google.protobuf.Message request)
            throws org.apache.ratis.shaded.com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.requestVote(controller, (org.apache.ratis.shaded.proto.RaftProtos.RequestVoteRequestProto)request);
            case 1:
              return impl.appendEntries(controller, (org.apache.ratis.shaded.proto.RaftProtos.AppendEntriesRequestProto)request);
            case 2:
              return impl.installSnapshot(controller, (org.apache.ratis.shaded.proto.RaftProtos.InstallSnapshotRequestProto)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final org.apache.ratis.shaded.com.google.protobuf.Message
            getRequestPrototype(
            org.apache.ratis.shaded.com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.apache.ratis.shaded.proto.RaftProtos.RequestVoteRequestProto.getDefaultInstance();
            case 1:
              return org.apache.ratis.shaded.proto.RaftProtos.AppendEntriesRequestProto.getDefaultInstance();
            case 2:
              return org.apache.ratis.shaded.proto.RaftProtos.InstallSnapshotRequestProto.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final org.apache.ratis.shaded.com.google.protobuf.Message
            getResponsePrototype(
            org.apache.ratis.shaded.com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.apache.ratis.shaded.proto.RaftProtos.RequestVoteReplyProto.getDefaultInstance();
            case 1:
              return org.apache.ratis.shaded.proto.RaftProtos.AppendEntriesReplyProto.getDefaultInstance();
            case 2:
              return org.apache.ratis.shaded.proto.RaftProtos.InstallSnapshotReplyProto.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc requestVote(.ratis.common.RequestVoteRequestProto) returns (.ratis.common.RequestVoteReplyProto);</code>
     */
    public abstract void requestVote(
        org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
        org.apache.ratis.shaded.proto.RaftProtos.RequestVoteRequestProto request,
        org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.RequestVoteReplyProto> done);

    /**
     * <code>rpc appendEntries(.ratis.common.AppendEntriesRequestProto) returns (.ratis.common.AppendEntriesReplyProto);</code>
     */
    public abstract void appendEntries(
        org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
        org.apache.ratis.shaded.proto.RaftProtos.AppendEntriesRequestProto request,
        org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.AppendEntriesReplyProto> done);

    /**
     * <code>rpc installSnapshot(.ratis.common.InstallSnapshotRequestProto) returns (.ratis.common.InstallSnapshotReplyProto);</code>
     */
    public abstract void installSnapshot(
        org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
        org.apache.ratis.shaded.proto.RaftProtos.InstallSnapshotRequestProto request,
        org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.InstallSnapshotReplyProto> done);

    public static final
        org.apache.ratis.shaded.com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.apache.ratis.shaded.proto.hadoop.HadoopProtos.getDescriptor().getServices().get(1);
    }
    public final org.apache.ratis.shaded.com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        org.apache.ratis.shaded.com.google.protobuf.Descriptors.MethodDescriptor method,
        org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
        org.apache.ratis.shaded.com.google.protobuf.Message request,
        org.apache.ratis.shaded.com.google.protobuf.RpcCallback<
          org.apache.ratis.shaded.com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.requestVote(controller, (org.apache.ratis.shaded.proto.RaftProtos.RequestVoteRequestProto)request,
            org.apache.ratis.shaded.com.google.protobuf.RpcUtil.<org.apache.ratis.shaded.proto.RaftProtos.RequestVoteReplyProto>specializeCallback(
              done));
          return;
        case 1:
          this.appendEntries(controller, (org.apache.ratis.shaded.proto.RaftProtos.AppendEntriesRequestProto)request,
            org.apache.ratis.shaded.com.google.protobuf.RpcUtil.<org.apache.ratis.shaded.proto.RaftProtos.AppendEntriesReplyProto>specializeCallback(
              done));
          return;
        case 2:
          this.installSnapshot(controller, (org.apache.ratis.shaded.proto.RaftProtos.InstallSnapshotRequestProto)request,
            org.apache.ratis.shaded.com.google.protobuf.RpcUtil.<org.apache.ratis.shaded.proto.RaftProtos.InstallSnapshotReplyProto>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final org.apache.ratis.shaded.com.google.protobuf.Message
        getRequestPrototype(
        org.apache.ratis.shaded.com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.apache.ratis.shaded.proto.RaftProtos.RequestVoteRequestProto.getDefaultInstance();
        case 1:
          return org.apache.ratis.shaded.proto.RaftProtos.AppendEntriesRequestProto.getDefaultInstance();
        case 2:
          return org.apache.ratis.shaded.proto.RaftProtos.InstallSnapshotRequestProto.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final org.apache.ratis.shaded.com.google.protobuf.Message
        getResponsePrototype(
        org.apache.ratis.shaded.com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.apache.ratis.shaded.proto.RaftProtos.RequestVoteReplyProto.getDefaultInstance();
        case 1:
          return org.apache.ratis.shaded.proto.RaftProtos.AppendEntriesReplyProto.getDefaultInstance();
        case 2:
          return org.apache.ratis.shaded.proto.RaftProtos.InstallSnapshotReplyProto.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        org.apache.ratis.shaded.com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends org.apache.ratis.shaded.proto.hadoop.HadoopProtos.RaftServerProtocolService implements Interface {
      private Stub(org.apache.ratis.shaded.com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final org.apache.ratis.shaded.com.google.protobuf.RpcChannel channel;

      public org.apache.ratis.shaded.com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void requestVote(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.RequestVoteRequestProto request,
          org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.RequestVoteReplyProto> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.apache.ratis.shaded.proto.RaftProtos.RequestVoteReplyProto.getDefaultInstance(),
          org.apache.ratis.shaded.com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.apache.ratis.shaded.proto.RaftProtos.RequestVoteReplyProto.class,
            org.apache.ratis.shaded.proto.RaftProtos.RequestVoteReplyProto.getDefaultInstance()));
      }

      public  void appendEntries(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.AppendEntriesRequestProto request,
          org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.AppendEntriesReplyProto> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          org.apache.ratis.shaded.proto.RaftProtos.AppendEntriesReplyProto.getDefaultInstance(),
          org.apache.ratis.shaded.com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.apache.ratis.shaded.proto.RaftProtos.AppendEntriesReplyProto.class,
            org.apache.ratis.shaded.proto.RaftProtos.AppendEntriesReplyProto.getDefaultInstance()));
      }

      public  void installSnapshot(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.InstallSnapshotRequestProto request,
          org.apache.ratis.shaded.com.google.protobuf.RpcCallback<org.apache.ratis.shaded.proto.RaftProtos.InstallSnapshotReplyProto> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(2),
          controller,
          request,
          org.apache.ratis.shaded.proto.RaftProtos.InstallSnapshotReplyProto.getDefaultInstance(),
          org.apache.ratis.shaded.com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.apache.ratis.shaded.proto.RaftProtos.InstallSnapshotReplyProto.class,
            org.apache.ratis.shaded.proto.RaftProtos.InstallSnapshotReplyProto.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        org.apache.ratis.shaded.com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public org.apache.ratis.shaded.proto.RaftProtos.RequestVoteReplyProto requestVote(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.RequestVoteRequestProto request)
          throws org.apache.ratis.shaded.com.google.protobuf.ServiceException;

      public org.apache.ratis.shaded.proto.RaftProtos.AppendEntriesReplyProto appendEntries(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.AppendEntriesRequestProto request)
          throws org.apache.ratis.shaded.com.google.protobuf.ServiceException;

      public org.apache.ratis.shaded.proto.RaftProtos.InstallSnapshotReplyProto installSnapshot(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.InstallSnapshotRequestProto request)
          throws org.apache.ratis.shaded.com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(org.apache.ratis.shaded.com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final org.apache.ratis.shaded.com.google.protobuf.BlockingRpcChannel channel;

      public org.apache.ratis.shaded.proto.RaftProtos.RequestVoteReplyProto requestVote(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.RequestVoteRequestProto request)
          throws org.apache.ratis.shaded.com.google.protobuf.ServiceException {
        return (org.apache.ratis.shaded.proto.RaftProtos.RequestVoteReplyProto) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.apache.ratis.shaded.proto.RaftProtos.RequestVoteReplyProto.getDefaultInstance());
      }


      public org.apache.ratis.shaded.proto.RaftProtos.AppendEntriesReplyProto appendEntries(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.AppendEntriesRequestProto request)
          throws org.apache.ratis.shaded.com.google.protobuf.ServiceException {
        return (org.apache.ratis.shaded.proto.RaftProtos.AppendEntriesReplyProto) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          org.apache.ratis.shaded.proto.RaftProtos.AppendEntriesReplyProto.getDefaultInstance());
      }


      public org.apache.ratis.shaded.proto.RaftProtos.InstallSnapshotReplyProto installSnapshot(
          org.apache.ratis.shaded.com.google.protobuf.RpcController controller,
          org.apache.ratis.shaded.proto.RaftProtos.InstallSnapshotRequestProto request)
          throws org.apache.ratis.shaded.com.google.protobuf.ServiceException {
        return (org.apache.ratis.shaded.proto.RaftProtos.InstallSnapshotReplyProto) channel.callBlockingMethod(
          getDescriptor().getMethods().get(2),
          controller,
          request,
          org.apache.ratis.shaded.proto.RaftProtos.InstallSnapshotReplyProto.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:ratis.hadoop.RaftServerProtocolService)
  }


  public static org.apache.ratis.shaded.com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  org.apache.ratis.shaded.com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Hadoop.proto\022\014ratis.hadoop\032\nRaft.proto" +
      "2\255\003\n\035CombinedClientProtocolService\022_\n\023su" +
      "bmitClientRequest\022$.ratis.common.RaftCli" +
      "entRequestProto\032\".ratis.common.RaftClien" +
      "tReplyProto\022b\n\020setConfiguration\022*.ratis." +
      "common.SetConfigurationRequestProto\032\".ra" +
      "tis.common.RaftClientReplyProto\022Z\n\014reini" +
      "tialize\022&.ratis.common.ReinitializeReque" +
      "stProto\032\".ratis.common.RaftClientReplyPr" +
      "oto\022k\n\021serverInformation\022+.ratis.common." +
      "ServerInformationRequestProto\032).ratis.co" +
      "mmon.ServerInformationReplyProto2\276\002\n\031Raf" +
      "tServerProtocolService\022Y\n\013requestVote\022%." +
      "ratis.common.RequestVoteRequestProto\032#.r" +
      "atis.common.RequestVoteReplyProto\022_\n\rapp" +
      "endEntries\022\'.ratis.common.AppendEntriesR" +
      "equestProto\032%.ratis.common.AppendEntries" +
      "ReplyProto\022e\n\017installSnapshot\022).ratis.co" +
      "mmon.InstallSnapshotRequestProto\032\'.ratis" +
      ".common.InstallSnapshotReplyProtoB:\n$org" +
      ".apache.ratis.shaded.proto.hadoopB\014Hadoo" +
      "pProtos\210\001\001\240\001\001b\006proto3"
    };
    org.apache.ratis.shaded.com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new org.apache.ratis.shaded.com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public org.apache.ratis.shaded.com.google.protobuf.ExtensionRegistry assignDescriptors(
              org.apache.ratis.shaded.com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    org.apache.ratis.shaded.com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new org.apache.ratis.shaded.com.google.protobuf.Descriptors.FileDescriptor[] {
          org.apache.ratis.shaded.proto.RaftProtos.getDescriptor(),
        }, assigner);
    org.apache.ratis.shaded.proto.RaftProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
